name: panorama
version: "1.5.0"
summary: A simple system monitor for Linux
description: |
    Panorama is a simple system monitor for Linux. It allows you to monitor system CPU and
    memory usage, and manage processes.
grade: stable
confinement: strict
icon: images/panorama.svg
type: app

build-packages:
    - g++
    - cmake
    - libsdl2-dev
    - libsdl2-image-dev
    - libcap-dev
    - libgl1-mesa-dev
    - python

apps:
    panorama:
        plugs:
            - x11
            - opengl
            - process-control
            - hardware-observe
            - system-observe
        command: desktop-launch $SNAP/bin/panorama
        desktop: ../desktop/panorama.desktop
    
parts:
    panorama:
        plugin: cmake
        source: .
        stage-packages:
            - libgl1-mesa-dri
            - libgl1-mesa-glx
            - libsdl2-2.0-0
            - libsdl2-image-2.0-0
            - libcap2
            - libc6
        after: [desktop-glib-only]

